//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yummy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecipeIndexDbEntities : DbContext
    {
        public RecipeIndexDbEntities()
            : base("name=RecipeIndexDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<IngredientsTable> IngredientsTables { get; set; }
        public DbSet<UserTable> UserTables { get; set; }
        public DbSet<RecipeTable> RecipeTables { get; set; }
    }
}
