//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yummy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientsTable
    {
        public string Ingredient { get; set; }
        public string Recipe_Array { get; set; }
    }
}
