//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yummy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeTable
    {
        public string Recipe_Category { get; set; }
        public string Recipe_Area { get; set; }
        public string Recipe_Ingredients { get; set; }
        public string Recipe_Tag { get; set; }
    }
}
